
server:
  port: 8081
  servlet:
    context-path: /springboot


spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  #redis
  redis:
    host: 192.168.161.150
    port: 6379
    jedis:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 30
        max-wait: 10
    timeout: 5000
    password: 123456


#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml

#logback
logging:
  level:
    root: info
    com.example.demo.controller.UserController: debug


#cacheManager 超时参数
cacheManager:
  timeout: 5000

